name: Node.js CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clone repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'berstend'
          repository: 'puppeteer-extra'
          branch: 'master'
          depth: 1

      - name: 'Fix for: error fsevents@2.1.2: The platform "linux" is incompatible with this module.'
        run: cd puppeteer-extra && npx json -I -f package.json -e 'this.resolutions={}'

      - name: Build packages
        run: |
          cd puppeteer-extra
          yarn install
          yarn bootstrap
          yarn build
          
      - name: Extract stealth.min.js
        run: |
          cd puppeteer-extra/packages/extract-stealth-evasions
          node index.js
          cp stealth.min.js ../../../
      
      - name: Commit stealth.min.js
        uses: EndBug/add-and-commit@v4
        with:
          add: 'stealth.min.js'
          force: true
          ref: 'main'
          message: 'Auto update stealth.min.js with latest module'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
